services:
  postgres:
    image: postgres:16
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neuro_scav_dev
    ports:
      - "5432:5432"
